package com.mycompany.saebu.gui.cobros;

import com.mycompany.saebu.gui.JFrameInicio;
import com.mycompany.saebu.gui.Alumno.ConsultarAlumno;
import com.mycompany.saebu.logica.clases.*;
import com.mycompany.saebu.logica.managers.*;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class JPanelRealizarPagoMensualidad extends javax.swing.JPanel {

    public JComboBox<String> getjComboBox1() {
        return jComboBox1;
    }

    private JFrameInicio parentFrame;
    private List<Inscripcion> insc = null;

    public JPanelRealizarPagoMensualidad() {
        initComponents();
        jComboBox1.setEnabled(false);
        jComboBox1.addItem("---");
        jTable1.getTableHeader().setReorderingAllowed(false);
        DefaultTableModel table = (DefaultTableModel) jTable1.getModel();
        table.setRowCount(0);
    }

    public void rellenarcombobox(Alumno alu) throws SQLException, ClassNotFoundException {
        if (insc != null) {
            insc.clear();
        }
        jTextField1.setText(alu.getNomyApe());
        jComboBox1.removeAllItems();
        jComboBox1.addItem("Todos");
        ManagerInscripcion mi = new ManagerInscripcion();
        insc = mi.consultarInscripciones(alu.getId_a());
        String nombre;
        for (int i = 0; i < insc.size(); i++) {
            nombre = insc.get(i).getDisciplina().getNombre();
            jComboBox1.addItem(nombre);
        }
        if (insc.isEmpty()) {
            jComboBox1.removeAllItems();
        }
    }

    public void crearTabla() {
        if (jComboBox1.getSelectedItem() != null) {
            if (jComboBox1.getSelectedItem().equals("Todos")) {
                DefaultTableModel table = (DefaultTableModel) jTable1.getModel();
                table.setRowCount(0);
                for (int j = 0; j < insc.size(); j++) {
                    for (int i = 0; i < insc.get(j).getCuotasMensuales().size(); i++) {
                        if (insc.get(j).getCuotasMensuales().get(i).getPnum() != -1) {
                            Object fila[] = {insc.get(j).getCuotasMensuales().get(i).getMes(), insc.get(j).getCuotasMensuales().get(i).getAnio(), insc.get(j).getCuotasMensuales().get(i).getPdc().getImporte(), insc.get(j).getCuotasMensuales().get(i).getPdc().getFecha(), insc.get(j).getCuotasMensuales().get(i).getPdc().getNroPago(), insc.get(j).getDisciplina().getNombre()};
                            table.addRow(fila);
                        }
                    }
                }
            } else {
                DefaultTableModel table = (DefaultTableModel) jTable1.getModel();
                table.setRowCount(0);
                for (int j = 0; j < insc.size(); j++) {
                    if (insc.get(j).getDisciplina().getNombre().equals(jComboBox1.getSelectedItem())) {
                        for (int i = 0; i < insc.get(j).getCuotasMensuales().size(); i++) {
                            if (insc.get(j).getCuotasMensuales().get(i).getPnum() != -1) {
                                Object fila[] = {insc.get(j).getCuotasMensuales().get(i).getMes(), insc.get(j).getCuotasMensuales().get(i).getAnio(), insc.get(j).getCuotasMensuales().get(i).getPdc().getImporte(), insc.get(j).getCuotasMensuales().get(i).getPdc().getFecha(), insc.get(j).getCuotasMensuales().get(i).getPdc().getNroPago(), insc.get(j).getDisciplina().getNombre()};
                                table.addRow(fila);
                            }
                        }
                    }
                }
            }
        } else {
            DefaultTableModel table = (DefaultTableModel) jTable1.getModel();
            table.setRowCount(0);
            jComboBox1.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButtonNuevoPago = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(156, 196, 228));
        setPreferredSize(new java.awt.Dimension(600, 530));
        setLayout(new java.awt.GridBagLayout());

        jPanel1.setBackground(new java.awt.Color(156, 196, 228));
        jPanel1.setPreferredSize(new java.awt.Dimension(600, 530));

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButtonNuevoPago.setText("Nuevo Pago");
        jButtonNuevoPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNuevoPagoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Pago de Mensualidad");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mes", "Año", "Importe", "Fec. Pago", "N° Recibo", "Disciplina"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jTextField1.setEditable(false);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Alumno:");

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(18, 18, 18)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(153, 153, 153)
                                    .addComponent(jLabel1))
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonNuevoPago, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNuevoPago, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 74;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 67, 0);
        add(jPanel1, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ConsultarAlumno vb = new ConsultarAlumno();
        vb.panel_aux = this;
        vb.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        if (jComboBox1.getItemCount() > 1) {
            if (jComboBox1.getSelectedItem() != null) {
                crearTabla();
            }
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButtonNuevoPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNuevoPagoActionPerformed
        try {
            if (insc != null) {
                JDialogConsultarDeudas ventana_nueva;
                ventana_nueva = new JDialogConsultarDeudas(parentFrame, true, insc, jTextField1.getText());
                //ventana_nueva.setInscripcion(insc);
                ventana_nueva.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(
                        null, // Componente padre (en este caso, ninguno)
                        "No selecciono ningun alumno.", // Mensaje
                        "ERROR", // Título de la ventana
                        JOptionPane.INFORMATION_MESSAGE // Tipo de mensaje (puede ser INFORMATION_MESSAGE, WARNING_MESSAGE, ERROR_MESSAGE, etc.)
                );
            }
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(JPanelRealizarPagoMensualidad.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonNuevoPagoActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed

    }//GEN-LAST:event_jTextField1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonNuevoPago;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
